---
# Common things for all OVF images
    - name: cloud-init                 | Disable EC2, OpenStack, CloudStack
      when: ansible_virtualization_type == "virtualbox"
      copy:
        content: |
          datasource_list: [ NoCloud, ConfigDrive, OpenNebula, DigitalOcean, Azure, AltCloud, OVF, MAAS, GCE, CloudSigma, SmartOS, None ]
          disable_ec2_metadata: true
        dest: /etc/cloud/cloud.cfg.d/90_disable-cloud.cfg
        mode: 0644
