---
provisioner:
  name: ansible_playbook
  hosts: 127.0.0.1
  ansible_verbose: true
  require_chef_for_busser: true
  roles_path: ansible/roles

transport:
  max_ssh_sessions: 5

platforms:
  - name: ovf
    driver:
      name: vagrant
      box: centos/7
      box_version: 1611.01
      cache_directory: false
      customize:
        memory: 1024
        createhd:
          filename: /tmp/some_random_name.vmdk
          size: 512
        storageattach:
          storagectl: IDE
          port: 1
          device: 0
          type: hdd
          medium: /tmp/some_random_name.vmdk
  - name: ami
    driver:
      name: ec2
      image_id: ami-6d1c2007
      instance_type: t2.micro
      aws_ssh_key_id: mykola
      security_group_ids: ["sg-4378343e"]
      subnet_id: subnet-4765a930
      region: us-east-1
      associate_public_ip: true
      tags:
        Name: test-kitchen
        created-by: test-kitchen
    transport:
      username: centos

suites:
  - name: mysql57
    provisioner:
      playbook: ansible/mysql57/main.yml
  - name: pmm
    provisioner:
      playbook: ansible/pmm/main.yml
