---
- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - cloud-node
    - mysql-init

  tasks:
    - name: Install console tools
      when: ansible_os_family == 'RedHat'
      yum: name={{ item }} state=installed
      with_items:
        - screen
        - vim
        - wget
        - lsof
        - telnet

    - name: Install Percona tools
      when: ansible_os_family == 'RedHat'
      yum: name={{ item }} state=installed
      with_items:
        - percona-toolkit
        - percona-xtrabackup
        - pmm-client

    - name: Add firewalld rule
      when: ansible_os_family == 'RedHat'
      firewalld: port={{ item }} permanent=true state=enabled immediate=yes
      with_items:
          - 3306/tcp
          - 42000-42005/tcp

    - name: cloud-init                 | Fix start-up sequence
      replace:
        dest: /usr/lib/systemd/system/cloud-final.service
        regexp: 'After=network.target'
        replace: 'After=mysqld.service network.target'

