---
- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - cloud-node
    - mysql-init

  tasks:
    - name: Install console tools
      when: ansible_os_family == 'RedHat'
      yum: name={{ item }} state=installed
      with_items:
        - screen
        - wget
        - telnet
        - curl
        - qpress
        - yum-utils
        - cronie
        - policycoreutils
        - policycoreutils-python
        - python-boto
        - python-setuptools
        - python-requests
        - rsync
        - sysstat
        - net-tools
        - lsof
        - vim
        - tmux
        - innotop

    - name: Install Percona tools
      when: ansible_os_family == 'RedHat'
      yum: name={{ item }} state=installed
      with_items:
        - percona-toolkit
        - percona-xtrabackup
        - pmm-client

    - name: Add mydumper repository
      when: ansible_os_family == 'RedHat'
      yum_repository:
        name: twindb_main
        description: twindb_main
        baseurl: https://packagecloud.io/twindb/main/el/7/$basearch
        gpgkey: https://packagecloud.io/twindb/main/gpgkey
        gpgcheck: no

    - name: Install mydumper
      when: ansible_os_family == 'RedHat'
      yum: name={{ item }} state=installed
      with_items:
        - mydumper

    - name: Add firewalld rule
      when: ansible_os_family == 'RedHat'
      firewalld: port={{ item }} permanent=true state=enabled immediate=yes
      with_items:
          - 3306/tcp
          - 42000-42010/tcp

    - name: cloud-init                 | Fix start-up sequence
      replace:
        dest: /usr/lib/systemd/system/cloud-final.service
        regexp: 'After=network.target'
        replace: 'After=mysqld.service network.target'

