---
# Initialize Postgres

    - name: Packages                   | Add Postgres repository
      when: ansible_os_family == 'RedHat'
      yum:
        name: https://repo.percona.com/ppg-11/yum/experimental/7/RPMS/x86_64/percona-postgresql11-11.5-1.el7.x86_64.rpm
        state: installed

    - name: Postgres                   | Install Postgres
      when: ansible_os_family == 'RedHat'
      yum:
        name:
          - percona-postgresql11-server
          - percona-postgresql11-contrib
          - percona-postgresql11
          - python-psycopg2
        state: installed

    - name: Postgres                   | Create Postgres data dir
      file: path={{ item }} state=directory owner=postgres group=postgres
      with_items:
        - /srv/postgres

    - name: Postgres                   | Create Postgres data cluster
      command: su postgres -c "/usr/pgsql-11/bin/initdb -D /srv/postgres"
