---
# Initialize Postgres

# !!! WARNING _experimental_ has to be replaced by _release_ after GA
    - name: Postgres                   | Add PostgreSQL YUM repository
      when: ansible_os_family == 'RedHat'
      yum_repository:
        name: percona-ppg-11-experimental
        description: PostgreSQL YUM repository - x86_64
        baseurl: http://repo.percona.com/ppg-11/yum/experimental/7/RPMS/x86_64
        gpgcheck: yes
        enabled: yes
        gpgkey: file:///etc/pki/rpm-gpg/PERCONA-PACKAGING-KEY

    - name: Postgres                   | Install Postgres
      when: ansible_os_family == 'RedHat'
      yum:
        name:
          - percona-postgresql11-server
          - percona-postgresql11-contrib
          - percona-postgresql11
          - python-psycopg2
        state: installed

    - name: Postgres                   | Create Postgres data dir
      file: path={{ item }} state=directory owner=postgres group=postgres
      with_items:
        - /srv/postgres

    - name: Postgres                   | Create Postgres data cluster
      command: su postgres -c "/usr/pgsql-11/bin/initdb -D /srv/postgres"
