---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: cloud-init                 | Change cloud user
      copy:
        content: |
          users:
            - name: pmmadmin
              lock_passwd: true
              gecos: Cloud User
              groups: [wheel, adm, systemd-journal]
              sudo: ["ALL=(ALL) NOPASSWD:ALL"]
              shell: /bin/bash
        dest: /etc/cloud/cloud.cfg.d/90_pmmadmin.cfg
        mode: 0644

    - name: cloud-init                 | Disable EC2, OpenStack, CloudStack
      copy:
        content: |
          datasource_list: [ NoCloud, ConfigDrive, OpenNebula, DigitalOcean, Azure, AltCloud, OVF, MAAS, GCE, CloudSigma, SmartOS, None ]
          disable_ec2_metadata: true
        dest: /etc/cloud/cloud.cfg.d/90_disable-cloud.cfg
        mode: 0644
