---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: cloud-init                 | Disable EC2, OpenStack, CloudStack
      copy:
        content: |
          datasource_list: [ NoCloud, ConfigDrive, OpenNebula, DigitalOcean, Azure, AltCloud, OVF, MAAS, GCE, CloudSigma, SmartOS, None ]
        dest: /etc/cloud/cloud.cfg.d/90_disable-cloud.cfg
        mode: 0644
