---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: cloud-init                 | Hide ssh field
      replace:
        dest: /usr/share/pmm-server/password-page/index.html
        regexp: 'input-group ssh'
        replace: 'input-group hidden ssh'

